---
vllm_inference_model_name: "meta-llama/Llama-3.1-8B-Instruct"
vllm_inference_gpu_memory_utilization: 0.90
vllm_inference_max_model_len: 4096
vllm_inference_port: 8000
vllm_inference_host: "0.0.0.0"
vllm_inference_tensor_parallel_size: 1
